website/music/urls.py
from . import views
from django.conf.urls import url

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),

    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

website/music/models.py
from django.db import models


class Album (models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=50)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song (models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
#from django.http import HttpResponse
from .models import Album, Song
#from django.template import loader
from django.shortcuts import render, get_object_or_404
#from django.http import Http404


def index(request):
    all_albums = Album.objects.all()
    # html = ''
    # for album in all_albums:
    #     url = '/music/' + str(album.id) + '/'
    #     html += '<a href="url">' + album.album_title + '</a><br>'

    # return HttpResponse(html)
    #template = loader.get_template('music/index.html')
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)


def details(request, album_id):
    # try:
    #    album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #    raise Http404("Album do not exist")
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/details.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {'album':Album, 'error_message':"Please enter a valid song!"})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/details.html', {'album': album})

website/music/templates/music/details.html
<img src ="{{  album.album_logo  }}">
<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>
{% if error_message  %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type = "radio" name = "song" id = "song{{ forloop.counter }}" value = "{{song.id}}" />
        <label for = "song{{ forloop.counter }}">
            {{ song.song_title }}

            {% if song.is_favorite  %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type = "submit" value = "Favorite"/>
</form>

website/music/templates/music/index.html
{% load staticfiles %}
<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<nav class = "navbar navbar-inverse">
     <div class="container-fluid">
        <div class="navbar-header">
             <button type ="button" data-toggle ="collapse"  class ="navbar-toggle" data-target="#anything" >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="{% url 'music:index' %}">MUSIC</a>
        </div>
        <div class="collapse navbar-collapse" id="anything">


            <ul class="nav navbar-nav">
                <li class="active">
                     <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                     </a>
                </li>
                <li class="">
                     <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                     </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" method="get" action="#" role="search">
                <div class="form-group">
                    <input name="q" class="form-control" type="text" value="" >
                </div>
                <button type="submit" class="btn btn-default">
                    Search
                </button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                     <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Albums
                     </a>
                </li>
                <li class="">
                     <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                     </a>
                </li>
            </ul>
        </div>
     </div>
</nav>


{% if all_albums %}
<h1>Here are all the albums: </h1>
<ul>
    {% for album in all_albums %}
    <li><a href="{% url 'music:details' album.id %}"> {{  album.album_title }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <h2>no albums</h2>
{% endif %}